"""Add tracking fields to orders

Revision ID: 07884ee0e539
Revises: 
Create Date: 2025-08-07 00:30:14.088848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '07884ee0e539'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_print_queues_id'), table_name='print_queues')
    op.drop_index(op.f('ix_print_queues_print_queue_id'), table_name='print_queues')
    op.drop_table('print_queues')
    op.drop_index(op.f('ix_print_queue_types_id'), table_name='print_queue_types')
    op.drop_index(op.f('ix_print_queue_types_name'), table_name='print_queue_types')
    op.drop_table('print_queue_types')
    op.drop_index(op.f('ix_printers_id'), table_name='printers')
    op.drop_table('printers')
    op.drop_index(op.f('ix_print_agents_id'), table_name='print_agents')
    op.drop_table('print_agents')
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('cancelled_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'cancelled_by')
    op.drop_column('orders', 'cancelled_at')
    op.drop_column('orders', 'updated_by')
    op.drop_column('orders', 'updated_at')
    op.create_table('print_agents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('token_hash', sa.VARCHAR(), nullable=False),
    sa.Column('print_queue_id', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('last_seen', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['print_queue_id'], ['print_queue_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_print_agents_id'), 'print_agents', ['id'], unique=False)
    op.create_table('printers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('default_printer', sa.BOOLEAN(), nullable=False),
    sa.Column('print_width', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_printers_id'), 'printers', ['id'], unique=False)
    op.create_table('print_queue_types',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('display_name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_print_queue_types_name'), 'print_queue_types', ['name'], unique=1)
    op.create_index(op.f('ix_print_queue_types_id'), 'print_queue_types', ['id'], unique=False)
    op.create_table('print_queues',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('print_queue_type_id', sa.INTEGER(), nullable=False),
    sa.Column('assigned_agent_id', sa.INTEGER(), nullable=True),
    sa.Column('print_data', sqlite.JSON(), nullable=False),
    sa.Column('print_queue_id', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('retry_count', sa.INTEGER(), nullable=False),
    sa.Column('max_retries', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['print_agents.id'], ),
    sa.ForeignKeyConstraint(['print_queue_type_id'], ['print_queue_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_print_queues_print_queue_id'), 'print_queues', ['print_queue_id'], unique=False)
    op.create_index(op.f('ix_print_queues_id'), 'print_queues', ['id'], unique=False)
    # ### end Alembic commands ###
